<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2022/04/02 11:56:10

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;port=3306;dbname=orangehrm_db',
  'username' => 'orangehrm',
  'password' => 'mme129689',
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
