<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2022/04/06 13:54:13
sfConfig::add(array(
  'mod_recruitmentapply_enabled' => true,
  'mod_recruitmentapply_view_class' => 'sfPHP',
));
